version: 1


formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%d.%m.%y   %H:%M:%S'


handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:  # only ERRORS go to the log-file
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    mode: w
    filename: /home/sushchikh/strbt_bot/logs/logs.txt
    encoding: UTF-8
    maxBytes: 8024
    backupCount: 3
loggers:
  sampleLogger:
    level: DEBUG
    handlers: [console, file]
    propagate: no
    exc_info: True
root:
  level: DEBUG
  handlers: [console, file]
